[package]
name = "savebreaker"
version = "0.1.0"
edition = "2024"

[dependencies]
analyze = { path = "../analyze" }
core = { path = "../core" }
io = { path = "../io" }
anyhow = { workspace = true }
clap = { version = "4", features = ["derive"] }
colored = "3.1.1"
