[package]
name = "savebreaker"
version = "0.1.0"
edition = "2024"

[dependencies]
analyze = { workspace = true }
core = { workspace = true }
io = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
colored = { workspace = true }
